shiftstack/ci-configs

Containerfile
ShellCheck is not included in the base image repository. Nor is it
required.
=> Containerfile: Remove failing package

Containerfile
Build fails: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18838/rehearse-18838-pull-ci-shiftstack-ci-configs-main-images/1399636370141483008
Removing until the need for a specific locale arises
=> Fix locale in container

Containerfile
Bash syntax is not allowed in the Containerfiles (nor in Dockerfiles);
invoking bash to interpret process substitution.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18838/rehearse-18838-pull-ci-shiftstack-ci-configs-main-images/1399704333196464128
=> Containerfile: Fix bash syntax in Containerfile

configs/default-cloud.yaml
default-cloud is a config that will be used to deploy a cloud with CI
defaults, but we want to be cloud agnostic (can be run in PSI,
VEXXHOST, etc) so we don't want to hardcode Ceph options.
Also we don't need the control plane IP, since we now separate it from the public network.
=> default-cloud: remove ceph device & set local cloudname

configs/kuryr-cloud.yaml
To deploy Kuryr cloud, you'll need to run:
* export IMAGE_NAME=rhel-8.2-x86_64
* export SERVER_USER=cloud-user
* ./provision.sh kuryr-cloud
* Once the cloud is deployed, you need to add floating IPs
to the `external` network.
=> Add new config for Kuryr cloud on OSP 16.1

configs/kuryr-cloud.yaml, provision.sh
To facilitate the maintenance of CI servers, by default let's add a few
people from our team. We can add more later if needed.
=> provision.sh: add SoS CI folks to SSH authorized keys

provision.sh
Change the environment variables default so we deploy the RHEL 8.2
image (with cloud-user user) instead of CentOS 8.
Indeed, we decided to deploy our CI clouds on OSP 16.1 which is more
realistic & stable from what our clients use.
=> provision.sh: change defaults to deploy OSP16.1 on RHEL 8.2

configs/kuryr-cloud.yaml, configs/osp-central.yaml
Since our provider gives us /24 for floating IPs we decided to give 40
floating IPs per cluster, so let's automate the creation of the
external network directly in dev-install by setting the right
parameters.
=> configs: automate floating ip network creation

configs/kuryr-cloud.yaml, configs/osp-central.yaml
The automation of the external network cannot
happens as we need to pre-create the fips
and include as allocation pools. This commit
removes the automation.
=> Remove automation of fips network creation

configs/mecha-central.yaml
OpenStack API runnings under WSGI have a common function to calculate the number of workers:
The value for os_workers is max between '(<# processors> / 2)' and '2' with
a cap of 12.
https://opendev.org/openstack/puppet-openstacklib/src/commit/495701901eabb24d28f2a2276275e1c1537133c1/lib/facter/os_workers.rb#L37-L38
On vexxhost machines, we have 96 cores, so each API can create up to 12 workers.
This has been problematic for us when deploying OpenShift with Kuryr which
consumes a lot of load balancers and Octavia is using more than half of the RAM available on the host
so we decided to reduce the number of workers to reduce the amount of RAM that will be consumed.
=> mecha: reduce workers for Octavia API

provision.sh
The hosts deployed by CI can get upgrades on day 2, so make sure we
keep the RHSM subscriptions on.
=> Set `rhsm_ephemeral` to false

configs/mecha-az0.yaml, configs/mecha-az1.yaml, configs/mecha-central.yaml
To counter an issue with Cinder snapshot testing with the Kubernetes CSI
driver test suite, we can set this parameter to True and this would
address our problem for now.
Full context is explained here:
https://bugzilla.redhat.com/show_bug.cgi?id=1989680
=> mecha: set CinderRbdFlattenVolumeFromSnapshot to True

provision.sh
post_install is used to run some bash commands at the end of a
deployment.
this is useful to automate environmental specifics, so let's just run
this step at the very end.
=> provision: run post_install

configs/nfv.yaml
We extended the slices to be 5 instead of 2, so we need more hugepages.
=> NFV: allocate more hugepages

configs/nfv.yaml
I'm reducing the hugepages because in a couple of redeployments, the
OpenStack API were not responsive, and Pacemaker was down. The host had
almost no RAM available...
With this patch, we now have 14GB of free RAM after a fresh deployment.
=> nfv: reduce hugepages to avoid pacemaker going down

provision.sh
When deploying AZ sites, now we need CENTRAL_NAME to be defined, because
we have no way to discover it for now.
=> provision: add a guard to check if CENTRAL_NAME is defined

provision.sh
This image has removed net.ifacenames=0 so we get consistent interface
names.
=> Update default image to rhel-84-shiftstack-ci

configs/nfv.yaml
Use `preferred` policy which is less restrictive and avoid scheduling
issues in our small footprint CI, where we don't have many CPUs to share
between the 2 NUMA nodes.
=> nfv: relax PCI NUMA Affinity Policy

configs/mecha-az0.yaml, configs/mecha-az1.yaml, configs/mecha-central.yaml
Vexxhost offers us jumbo frames, so we can go up to 9000 for MTU. Let's
just use 1600 for now, which works for our needs, but we need the tenant
networks to be above the default 1300 because we deploy OCP, which does
double encapsulation with OVN on OVN and with IPv6 it's being
problematic, see https://issues.redhat.com/browse/OCPBUGS-2921
=> Adjust MTU for Mecha

configs/hwoffload.yaml
In order to access externally the OSP Instances using the IPv6 address, the router must be configured with the dual-stack network set as external gateway.
=> Enable external IPv6 connectivity

configs/hwoffload.yaml
There are some pre-created resources in the hwoffload cloud that shouldn't be taken into account when the prune script is ran. This commit sets the tag to those resources to avoid them being cleaned up.
=> Set shiftstack-prune=keep tag to pre-created resources

configs/hwoffload.yaml
Given the minimun MTU value suported for IPv6 is 1280, we need to increase the MTU of neutron to 1450, while maintaining the value previously
supported for the bridges.
=> Update MTU used in the HWoffload cloud

configs/nfv.yaml
NFV jobs are failing due to insufficient NovaComputeCpuShared cores in the NFV Cloud to deploy controlplane and bootstrap nodes. Changes applied:
- Increasing NovaComputeCpuSharedSet to 60 cores. So isolated_cores (OvsPmdCoreList  + NovaComputeCpuDedicatedSet) will reduced from 56 cores to 36 (allowing at least 4 NFV compute nodes or 4 NFV jobs). 
- Removing the assigned OvsPmdCoreList from the NovaComputeCpuDedicatedSet list. NovaComputeCpuDedicatedSet: Exclude all cores from the OvsPmdCoreList. Pair the sibling threads together. Include all remaining cores.
=> OSASINFRA-3551: Updating the NovaComputeCpu Dedicated and Shared Set in nfv config

configs/nfv.yaml
I realized that the bootstrap machine needs hugepages for NFV cluster deployment. Bootstrap uses the same flavor as Controlplane machines, so masters need a flavor with hugepages; therefore, the hugepage configuration should be the following:
```
16384 / 1024 = 16    # flavour.memory_mb / 1024
16 * ( 5 * 4 ) = 320    # no. hugepages per instance * ( no. instances * no. clusters)
320 + 2 + 2 = 324        # no. hugepages for all instances + no. hugepages for OVS-DPDK
```
=> OSASINFRA-3551: Increase hugepages in NFV config

configs/hwoffload.yaml
We are adding a new CI job to test single stack ipv6.
However, our OpenStack endpoints are only on ipv4 and it's going to be
difficult to change that in dev-install. So in the meantime, we use
`openstack-proxy` tool from
https://github.com/pierreprinetti/openstack-proxy.
This will create an endpoint on a port that is not open to the firewall,
so it's not available from the Internet. But that's fine because the
only user of this endpoint should be the OCP machines that are deployed
and are single stack v6 already and within the same subnet as the
endpoint so there is no need to open IPtables.
=> hwoffload: add openstack-proxy for ipv6 endpoint

configs/hwoffload.yaml
We don't need bigger disk anymore since we attach a large cinder volume
used for the mirror registry.
=> hwoffload: revert change on m1.small

configs/hwoffload.yaml, configs/mecha-az0.yaml, configs/mecha-central.yaml
This PR is an effort to consolidate ci-config yamls, mecha-central, mecha-az0 and hwoffload to support all general jobs (not NFV)
This PR :
- Correct typo:
```
standalone_extra_config:
- octavia::wsgi::apache:workers: 4
+ octavia::wsgi::apache::workers: 4
```
- Add proxy and externallb job support on hwoffload cloud
- Remove Object Storage service on hwoffload cloud
- Update the OS_CLIENT_CONFIG_FILE path
- Leave a blank line, after post_install section, with no space at the start to well introduce the post_install into the local-overrides.yaml
=> OSASINFRA-3562: Update ci-config yamls for general job support
